name: StartupJobs monitor

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write


jobs:
  check_jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install browser
        run: |
          playwright install chromium

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run monitor
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python job_monitor.py

      - name: Save state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add known_jobs.json
          git commit -m "Update known jobs" || exit 0
          git push